# permissions for end users to view ipfsclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipfscluster-viewer-role
rules:
- apiGroups:
  - cluster.ipfs.io
  resources:
  - ipfsclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.ipfs.io
  resources:
  - ipfsclusters/status
  verbs:
  - get
